base_url = "https://fapi.binance.com/fapi"
  
float1_list = ['BNXUSDT', 'AAVEUSDT', 'EGLDUSDT', 'KSMUSDT', 'ZENUSDT', 'TRBUSDT', 'ARUSDT', 'ENSUSDT', 'LPTUSDT','DOTUSDT', 'UNFIUSDT', 'FILUSDT', 'APTUSDT','QNTUSDT', 'FXSUSDT','XVSUSDT','CYBERUSDT','NMRUSDT','INJUSDT','BONDUSDT','BSVUSDT','GASUSDT','DYDXUSDT','SUIUSDT','ZRXUSDT','WAVESUSDT','THETAUSDT','SNXUSDT','API3USDT','ARBUSDT','BANDUSDT','OPUSDT','QTUMUSDT','ORDIUSDT','BALUSDT','RNDRUSDT','ALICEUSDT','ILVUSDT','HIGHUSDT','MANTAUSDT','MAVIAUSDT','RLCUSDT','DYMUSDT','STRKUSDT','RONINUSDT','PORTALUSDT','AXLUSDT','TONUSDT','AEVOUSDT','ETHFIUSDT','TNSRUSDT','WUSDT','SAGAUSDT','IOUSDT','ZROUSDT']
float2_list = ['BNBUSDT', 'NEOUSDT', 'ATOMUSDT','GMXUSDT','SSVUSDT','ETCUSDT','LINKUSDT','AUCTIONUSDT','ACEUSDT','MOVRUSDT','METISUSDT','OMNIUSDT']
float3_list = ['BTCUSDT', 'ETHUSDT', 'YFIUSDT', 'MKRUSDT', 'DEFIUSDT', 'XMRUSDT', 'BCHUSDT', 'ZECUSDT', 'COMPUSDT', 'DASHUSDT','LTCUSDT','TAOUSDT']


# 这里是需要修改的部分

#你的api_key 和 secret_key 
api_key = '1zd8WOkPmkDJYrya4gwh9qOldE3afaJSBzaC2APBXT1XCrFBIXkxorxqqMH'
secret_key = 'j4wNZmLKCz7ShKEaVxfGB5JzdfagafWmehj8tApyAoJFE4CSHNRoYpiceePRYZ'

listen_key = '6BNNkvtCcQjgagaB4qrNPipWxu6m8TXwSQ1ZQCnOF83pHsUM3XZkTgNfkjTr0I1'

# 开仓的数量
balance_open = 20

# 开仓的币种
params_open = [ 
    "movrusdt@kline_1m"
]
